export const musicas = [
    {
        nome:["Erguei", "as mãos"],
        foto:"/padre1.jpeg",
        cor:"#3d99eb",
        cor2:"#2e364f",
        musica:"/erguei.mp3",
        artista:"Pr. Marcelo Horse",
        album:"Cações Para Crianças",
        letras:[
            [0.06,"Quem se lembra?"],
            [0.07,"Não ainda, né?"],
            [0.11,"Faz tempo, hein!"],
            [0.19,"Ninguém descobriu ainda?"],
            [0.21,"Opa! Esse descobriu"],
            [0.22,"Erguei as mãos e dai glória a Deus"],
            [0.26,"Erguei as mãos e dai glória a Deus"],
            [0.29,"Erguei as mãos"],
            [0.31,"E cantai como os filhos do Senhor"],
            [0.38,"Os animaizinhos subiram de dois em dois"],
            [0.41,"Os animaizinhos subiram de dois em dois"],
            [0.44,"O elefante"],
            [0.47,"E os passarinhos, como os filhos do Senhor(Para não!)"],
            [0.51,"Os animaizinhos subiram de dois em dois"],
            [0.56,"Os animaizinhos subiram de dois em dois"],
            [0.59,"A minhoquinha"],
            [1.01,"E os pinguins, como os filhos do Senhor"],
            [1.06,"Os animaizinhos subiram de dois em dois"],
            [1.09,"Os animaizinhos subiram de dois em dois"],
            [1.13,"O canguru"],
            [1.15,"E o sapinho, como os filhos do Senhor"],
            [1.21,"Deus disse a Noé: constrói uma arca"],
            [1.27,"Que seja feita"],
            [1.29,"De madeira para os filhos do Senhor"],
            [1.32,"Por isso...!"],
            [1.36,"Erguei as mãos e dai glória a Deus"],
            [1.39,"Erguei as mãos e dai glória a Deus"],
            [1.43,"Erguei as mãos"],
            [1.44,"E cantai como os filhos do Senhor"],
            [1.51,"Erguei as mãos e dai glória a Deus"],
            [1.55,"Erguei as mãos e dai glória a Deus"],
            [1.58,"Erguei as mãos"],
            [2.00,"E cantai como os filhos do Senhor(De Novo)"],
            [2.07,"Erguei as mãos e dai glória a Deus"],
            [2.11,"Erguei as mãos e dai glória a Deus"],
            [2.14,"Erguei as mãos"],
            [2.15,"E cantai como os filhos do Senhor"],
            [2.19,"E atenção agora, porque..."],
            [2.21,"O senhor tem muitos filhos"],
            [2.24,"Todos filhos ele tem"],
            [2.27,"Eu sou um deles, você também"],
            [2.31,"Louvemos ao senhor (braço direito!)"],
            [2.34,"O senhor tem muitos filhos"],
            [2.36,"Muitos filhos ele tem"],
            [2.41,"Eu sou um deles, você também"],
            [2.45,"Louvemos ao senhor"],
            [2.47,"Braço direito, braço esquerdo"],
            [2.49,"O senhor tem muitos filhos"],
            [2.53,"Muitos filhos ele tem (Até que eu tô em forma)"],
            [2.56,"Eu sou um deles, você também"],
            [3.00,"Louvemos ao senhor"],
            [3.02,"Braço direito, braço esquerdo, "],
            [3.03,"Perna direita"],
            [3.04,"O senhor tem muitos filhos"],
            [3.05,"Muitos filhos ele tem"],
            [3.11,"Eu sou um deles, você também"],
            [3.15,"Louvemos ao senhor"],
            [3.18,"Braço direito, braço esquerdo"],
            [3.19,"Perna direita, perna esquerda"],
            [3.21,"O senhor tem muitos filhos (muitos filhos)"],
            [3.25,"Muitos filhos ele tem"],
            [3.28,"Eu sou um deles, você também (Que saudade dessa música)"],
            [3.32,"Louvemos ao senhor"],
            [3.34,"Braço direito, braço esquerdo"],
            [3.36,"Perna direita, perna esquerda"],
            [3.38,"Balança a cabeça"],
            [3.39,"O senhor tem muitos filhos"],
            [3.42,"Muitos filhos ele tem"],
            [3.46,"Eu sou um deles, você também"],
            [3.49,"Louvemos ao senhor"],
            [3.52,"Braço direito, braço esquerdo"],
            [3.54,"Perna direita, perna esquerda"],
            [3.55,"Balança a cabeça, dá uma voltinha"],
            [3.57,"O senhor tem muitos filhos"],
            [4.00,"Muitos filhos ele tem(Bonita Cruz)"],
            [4.04,"Eu sou um deles, você também"],
            [4.07,"Louvemos ao senhor"],
            [4.09,"Braço direito, braço esquerdo"],
            [4.11,"Perna direita, perna esquerda"],
            [4.12,"Balança a cabeça, dá uma voltinha"],
            [4.13,"Dá um pulinho"],
            [4.15,"O senhor tem muitos filhos(Para não)"],
            [4.18,"Muitos filhos ele tem"],
            [4.19,"Eu sou um deles, você também"],
            [4.23,"Louvemos ao senhor"],
            [4.26,"Braço direito, braço esquerdo"],
            [4.27,"Perna direita, perna esquerda"],
            [4.28,"Balança a cabeça, dá uma voltinha"],
            [4.29,"Dá um pulinho e abraça o irmão"],
            [4.31,"Uôh, que saudade dessa música!"],
        ]
    },
    {
        nome:["Espelhos", "Mágicos"],
        foto:"/g3.jpg",
        cor:"#4A8D4E",
        cor2:"rgb(19 24 39)",
        musica:"/espelho.mp3",
        artista:"Oficina G3",
        album:"Indiferença",
        letras:[
            [0.24,"Os homens e seus espelhos mágicos"],
            [0.32, "Nada veem além de si mesmos"],
            [0.39,"Se esqueceram daquele que um dia"],
            [0.43, "Esteve entre nós"],
            [0.47, "E que veio cumprir"],
            [0.50, "Segundo, já estava escrito"],
            [0.57, "Nasceu"],
            [0.59, "Sofreu"],
            [1.01, "Morreu ,por nós"],
            [1.05, "Seu sangue lá na cruz derramou"],
            [1.11, "Nasceu, sofreu..."],
            [1.17, "Os homens e seus espelhos mágicos"],
            [1.24, "Só vêm um Cristo vencido em dor"],
            [1.32, "Não conhecem a cruz vazia"],
            [1.36,"Pois ressucitou"],
            [1.39, "E nem o toque de vida"],
            [1.44, "Do Filho do amor"],
            [1.58, "Nasceu"],
            [1.51,"Sofreu"],
            [1.53, "Morreu, por nós"],  
            [1.58, "Seu sangue lá na cruz derramou"],
            [2.05, "Nasceu"],
            [2.06, "Sofreu"],
            [2.09, "Morreu, por nós"],
            [2.13, "Seu sangue lá na cruz derramou"],
            [2.19, "Na cruz lutou"],
            [2.24, "Na cruz venceu"],
            [2.28,"E sua vida nos deu"],
            [2.31,"Pra que a vida"],
            [2.33, "Estivesse em nós!!!"],
            [2.42,"(Solo)"],
            [3.12, "Nasceu"],
            [3.15, "Sofreu"],
            [3.16, "Morreu, por nós"],
            [3.22,"Seu sangue lá na cruz derramou"],
            [3.28,"Nasceu"],
            [3.29, "Sofreu"],
            [3.31, "Morreu por nós"],
            [3.36,"Seu sangue lá na cruz derramou"],
            [3.42,"Na cruz lutou"],
            [3.47, "Na cruz venceu"],
            [3.51,"E sua vida nos deu"],
            [3.54,"Pra que a vida estivesse em nós"],
            [4.03,"Estivesse em nós"],
            [4.12,"Estivesse em nós"]
        ]
    },
    {
        nome:["A Tempestade", "vai passar"],
        foto:"/g3.jpg",
        cor:"#4A8D4E",
        cor2:"rgb(19 24 39)",
        musica:"/tempestade.mp3",
        artista:"Padre Reginaldo Manzotti",
        album:"Amigos da fé",
        letras:[
            [0.24,"Como é bom estar aqui"],
            [0.32, "Em meio a tantas provações"],
            [0.39,"Saber que posso confiar em meu Senhor"],
            [0.43, "E acreditar que ele nunca faltará"],
            [0.47, "A tempestade vai passar"],
            [0.50, "Por sobre as ondas, confiante andarei"],
            [0.57, "Tribulações vencerei"],
            [0.59, "As aflições superarei"],
            [1.01, "Deus provê, eu sei que proverá"],
            [0.47, "A tempestade vai passar"],
            [0.50, "Por sobre as ondas, confiante andarei"],
            [0.57, "Tribulações vencerei"],
            [0.59, "As aflições superarei"],
            [1.01, "Deus provê, eu sei que proverá"],
            [1.05, "Neste bravo mar da vida"],
            [1.11, "Ventos vêm me atormentar"],
            [1.17, "Os homens e seus espelhos mágicos"],
            [1.24, "Nesta rocha firme e forte que é meu Deus"],
            [1.32, "Não temerei nele posso confiar"],
            [0.47, "A tempestade vai passar"],
            [0.50, "Por sobre as ondas, confiante andarei"],
            [0.57, "Tribulações vencerei"],
            [0.59, "As aflições superarei"],
            [1.01, "Deus provê, eu sei que proverá"],
            [0.47, "A tempestade vai passar"],
            [0.50, "Por sobre as ondas, confiante andarei"],
            [0.57, "Tribulações vencerei"],
            [0.59, "As aflições superarei"],
            [1.01, "Deus provê, eu sei que proverá"],
        ]
    }
]