export const musicas = [
    {
        nome:"Erguei as mãos",
        foto:"/padre1.jpeg",
        cor:"#3DCEEB",
        musica:"/j.mp3",
        artista:"Pr. Marcelo Horse",
        album:"Cações Para Crianças",
        musica:"/j.mp3",
        letras:[
            [0.06,"Quem se lembra?"],
            [0.07,"Não ainda, né?"],
            [0.11,"Faz tempo, hein!"],
            [0.19,"Ninguém descobriu ainda?"],
            [0.21,"Opa! Esse descobriu"],
            [0.22,"Erguei as mãos e dai glória a Deus"],
            [0.26,"Erguei as mãos e dai glória a Deus"],
            [0.29,"Erguei as mãos"],
            [0.31,"E cantai como os filhos do Senhor"],
            [0.28,"Os animaizinhos subiram de dois em dois"],
            [0.41,"Os animaizinhos subiram de dois em dois"],
            [0.44,"O elefante"],
            [0.47,"E os passarinhos, como os filhos do Senhor(Para não!)"],
            [0.51,"Os animaizinhos subiram de dois em dois"],
            [0.56,"Os animaizinhos subiram de dois em dois"],
            [0.59,"A minhoquinha"],
            [1.01,"E os pinguins, como os filhos do Senhor"],
            [1.06,"Os animaizinhos subiram de dois em dois"],
            [1.09,"Os animaizinhos subiram de dois em dois"],
            [1.13,"O canguru"],
            [1.15,"E o sapinho, como os filhos do Senhor"],
            [1.20,"Deus disse a Noé: constrói uma arca"],
            [1.24,"Deus disse a Noé: constrói uma arca"],
            [1.27,"Que seja feita"],
            [1.29,"De madeira para os filhos do Senhor"],
            [1.32,"Por isso...!"],
            [1.36,"Erguei as mãos e dai glória a Deus"],
            [1.39,"Erguei as mãos e dai glória a Deus"],
            [1.43,"Erguei as mãos"],
            [1.44,"E cantai como os filhos do Senhor"],
            [1.51,"Erguei as mãos e dai glória a Deus"],
            [1.55,"Erguei as mãos e dai glória a Deus"],
            [1.58,"Erguei as mãos"],
            [2.00,"E cantai como os filhos do Senhor(De Novo)"],
            [2.07,"Erguei as mãos e dai glória a Deus"],
            [2.11,"Erguei as mãos e dai glória a Deus"],
            [2.14,"Erguei as mãos"],
            [2.15,"E cantai como os filhos do Senhor"],
            [2.19,"E atenção agora, porque..."],
            [2.21,"O senhor tem muitos filhos"],
            [2.24,"Todos filhos ele tem"],
            [2.27,"Eu sou um deles, você também"],
            [2.31,"Louvemos ao senhor (braço direito!)"],
            [2.34,"O senhor tem muitos filhos"],
            [2.28,"Muitos filhos ele tem"],
            [2.41,"Eu sou um deles, você também"],
            [2.25,"Louvemos ao senhor"],
            [2.47,"Braço direito, braço esquerdo"],
            [2.49,"O senhor tem muitos filhos"],
            [2.53,"Muitos filhos ele tem (Até que eu tô em forma)"],
            [2.56,"Eu sou um deles, você também"],
            [3.00,"Louvemos ao senhor"],
            [3.02,"Braço direito, braço esquerdo, "],
            [3.04,"Perna direita"],
            [3.05,"Muitos filhos ele tem"],
            [3.11,"Eu sou um deles, você também"],
            [3.15,"Louvemos ao senhor"],
            [3.18,"Braço direito, braço esquerdo"],
            [3.09,"Perna direita, perna esquerda"],
            [3.21,"O senhor tem muitos filhos (muitos filhos)"],
            [3.25,"Muitos filhos ele tem"],
            [3.28,"Eu sou um deles, você também (Que saudade dessa música)"],
            [3.32,"Louvemos ao senhor"],
            [3.34,"Braço direito, braço esquerdo"],
            [3.36,"Perna direita, perna esquerda"],
            [3.38,"Balança a cabeça"],
            [3.39,"O senhor tem muitos filhos"],
            [3.42,"Muitos filhos ele tem"],
            [3.46,"Eu sou um deles, você também"],
            [3.49,"Louvemos ao senhor"],
            [3.52,"Braço direito, braço esquerdo"],
            [3.54,"Perna direita, perna esquerda"],
            [3.55,"Balança a cabeça, dá uma voltinha"],
            [3.57,"O senhor tem muitos filhos"],
            [4.00,"Muitos filhos ele tem(Bonita Cruz)"],
            [4.04,"Eu sou um deles, você também"],
            [4.07,"Louvemos ao senhor"],
            [4.09,"Braço direito, braço esquerdo"],
            [4.11,"Perna direita, perna esquerda"],
            [4.12,"Balança a cabeça, dá uma voltinha"],
            [4.13,"Dá um pulinho"],
            [4.15,"O senhor tem muitos filhos(Para não)"],
            [4.17,"Muitos filhos ele tem"],
            [4.20,"Eu sou um deles, você também"],
            [4.23,"Louvemos ao senhor"],
            [4.26,"Braço direito, braço esquerdo"],
            [4.27,"Perna direita, perna esquerda"],
            [4.28,"Balança a cabeça, dá uma voltinha"],
            [4.29,"Dá um pulinho e abraça o irmão"],
            [4.31,"Uôh, que saudade dessa música!"],
        ]
    }
]